import { Direction } from './constants'

// TODO: These values were generated in C++ and pasted here. Maybe write a way to do it here without
// relying on C++.
export abstract class GameCache {
  public static squareToNeighboringSquares: Array<Array<number>> =
  [
    [8, 1, 9],
    [0, 8, 9, 2, 10],
    [1, 9, 10, 3, 11],
    [2, 10, 11, 4, 12],
    [3, 11, 12, 5, 13],
    [4, 12, 13, 6, 14],
    [5, 13, 14, 7, 15],
    [6, 14, 15],
    [0, 16, 1, 9, 17],
    [0, 8, 16, 1, 17, 2, 10, 18],
    [1, 9, 17, 2, 18, 3, 11, 19],
    [2, 10, 18, 3, 19, 4, 12, 20],
    [3, 11, 19, 4, 20, 5, 13, 21],
    [4, 12, 20, 5, 21, 6, 14, 22],
    [5, 13, 21, 6, 22, 7, 15, 23],
    [6, 14, 22, 7, 23],
    [8, 24, 9, 17, 25],
    [8, 16, 24, 9, 25, 10, 18, 26],
    [9, 17, 25, 10, 26, 11, 19, 27],
    [10, 18, 26, 11, 27, 12, 20, 28],
    [11, 19, 27, 12, 28, 13, 21, 29],
    [12, 20, 28, 13, 29, 14, 22, 30],
    [13, 21, 29, 14, 30, 15, 23, 31],
    [14, 22, 30, 15, 31],
    [16, 32, 17, 25, 33],
    [16, 24, 32, 17, 33, 18, 26, 34],
    [17, 25, 33, 18, 34, 19, 27, 35],
    [18, 26, 34, 19, 35, 20, 28, 36],
    [19, 27, 35, 20, 36, 21, 29, 37],
    [20, 28, 36, 21, 37, 22, 30, 38],
    [21, 29, 37, 22, 38, 23, 31, 39],
    [22, 30, 38, 23, 39],
    [24, 40, 25, 33, 41],
    [24, 32, 40, 25, 41, 26, 34, 42],
    [25, 33, 41, 26, 42, 27, 35, 43],
    [26, 34, 42, 27, 43, 28, 36, 44],
    [27, 35, 43, 28, 44, 29, 37, 45],
    [28, 36, 44, 29, 45, 30, 38, 46],
    [29, 37, 45, 30, 46, 31, 39, 47],
    [30, 38, 46, 31, 47],
    [32, 48, 33, 41, 49],
    [32, 40, 48, 33, 49, 34, 42, 50],
    [33, 41, 49, 34, 50, 35, 43, 51],
    [34, 42, 50, 35, 51, 36, 44, 52],
    [35, 43, 51, 36, 52, 37, 45, 53],
    [36, 44, 52, 37, 53, 38, 46, 54],
    [37, 45, 53, 38, 54, 39, 47, 55],
    [38, 46, 54, 39, 55],
    [40, 56, 41, 49, 57],
    [40, 48, 56, 41, 57, 42, 50, 58],
    [41, 49, 57, 42, 58, 43, 51, 59],
    [42, 50, 58, 43, 59, 44, 52, 60],
    [43, 51, 59, 44, 60, 45, 53, 61],
    [44, 52, 60, 45, 61, 46, 54, 62],
    [45, 53, 61, 46, 62, 47, 55, 63],
    [46, 54, 62, 47, 63],
    [48, 49, 57],
    [48, 56, 49, 50, 58],
    [49, 57, 50, 51, 59],
    [50, 58, 51, 52, 60],
    [51, 59, 52, 53, 61],
    [52, 60, 53, 54, 62],
    [53, 61, 54, 55, 63],
    [54, 62, 55]
  ]
  public static squareToNeighboringNonDiagonalSquares: Array<Array<number>> = 
  [
    [8, 1],
    [0, 9, 2],
    [1, 10, 3],
    [2, 11, 4],
    [3, 12, 5],
    [4, 13, 6],
    [5, 14, 7],
    [6, 15],
    [0, 16, 9],
    [8, 1, 17, 10],
    [9, 2, 18, 11],
    [10, 3, 19, 12],
    [11, 4, 20, 13],
    [12, 5, 21, 14],
    [13, 6, 22, 15],
    [14, 7, 23],
    [8, 24, 17],
    [16, 9, 25, 18],
    [17, 10, 26, 19],
    [18, 11, 27, 20],
    [19, 12, 28, 21],
    [20, 13, 29, 22],
    [21, 14, 30, 23],
    [22, 15, 31],
    [16, 32, 25],
    [24, 17, 33, 26],
    [25, 18, 34, 27],
    [26, 19, 35, 28],
    [27, 20, 36, 29],
    [28, 21, 37, 30],
    [29, 22, 38, 31],
    [30, 23, 39],
    [24, 40, 33],
    [32, 25, 41, 34],
    [33, 26, 42, 35],
    [34, 27, 43, 36],
    [35, 28, 44, 37],
    [36, 29, 45, 38],
    [37, 30, 46, 39],
    [38, 31, 47],
    [32, 48, 41],
    [40, 33, 49, 42],
    [41, 34, 50, 43],
    [42, 35, 51, 44],
    [43, 36, 52, 45],
    [44, 37, 53, 46],
    [45, 38, 54, 47],
    [46, 39, 55],
    [40, 56, 49],
    [48, 41, 57, 50],
    [49, 42, 58, 51],
    [50, 43, 59, 52],
    [51, 44, 60, 53],
    [52, 45, 61, 54],
    [53, 46, 62, 55],
    [54, 47, 63],
    [48, 57],
    [56, 49, 58],
    [57, 50, 59],
    [58, 51, 60],
    [59, 52, 61],
    [60, 53, 62],
    [61, 54, 63],
    [62, 55]
  ]
  public static squareToDirectionToLine: Array<Array<Array<number>>> =
  [
    [[8, 16, 24, 32, 40, 48, 56], [9, 18, 27, 36, 45, 54, 63], [1, 2, 3, 4, 5, 6, 7], [], [], [], [], [], []],
    [[9, 17, 25, 33, 41, 49, 57], [10, 19, 28, 37, 46, 55], [2, 3, 4, 5, 6, 7], [], [], [], [0], [8], []],
    [[10, 18, 26, 34, 42, 50, 58], [11, 20, 29, 38, 47], [3, 4, 5, 6, 7], [], [], [], [1, 0], [9, 16], []],
    [[11, 19, 27, 35, 43, 51, 59], [12, 21, 30, 39], [4, 5, 6, 7], [], [], [], [2, 1, 0], [10, 17, 24], []],
    [[12, 20, 28, 36, 44, 52, 60], [13, 22, 31], [5, 6, 7], [], [], [], [3, 2, 1, 0], [11, 18, 25, 32], []],
    [[13, 21, 29, 37, 45, 53, 61], [14, 23], [6, 7], [], [], [], [4, 3, 2, 1, 0], [12, 19, 26, 33, 40], []],
    [[14, 22, 30, 38, 46, 54, 62], [15], [7], [], [], [], [5, 4, 3, 2, 1, 0], [13, 20, 27, 34, 41, 48], []],
    [[15, 23, 31, 39, 47, 55, 63], [], [], [], [], [], [6, 5, 4, 3, 2, 1, 0], [14, 21, 28, 35, 42, 49, 56], []],
    [[16, 24, 32, 40, 48, 56], [17, 26, 35, 44, 53, 62], [9, 10, 11, 12, 13, 14, 15], [1], [0], [], [], [], []],
    [[17, 25, 33, 41, 49, 57], [18, 27, 36, 45, 54, 63], [10, 11, 12, 13, 14, 15], [2], [1], [0], [8], [16], []],
    [[18, 26, 34, 42, 50, 58], [19, 28, 37, 46, 55], [11, 12, 13, 14, 15], [3], [2], [1], [9, 8], [17, 24], []],
    [[19, 27, 35, 43, 51, 59], [20, 29, 38, 47], [12, 13, 14, 15], [4], [3], [2], [10, 9, 8], [18, 25, 32], []],
    [[20, 28, 36, 44, 52, 60], [21, 30, 39], [13, 14, 15], [5], [4], [3], [11, 10, 9, 8], [19, 26, 33, 40], []],
    [[21, 29, 37, 45, 53, 61], [22, 31], [14, 15], [6], [5], [4], [12, 11, 10, 9, 8], [20, 27, 34, 41, 48], []],
    [[22, 30, 38, 46, 54, 62], [23], [15], [7], [6], [5], [13, 12, 11, 10, 9, 8], [21, 28, 35, 42, 49, 56], []],
    [[23, 31, 39, 47, 55, 63], [], [], [], [7], [6], [14, 13, 12, 11, 10, 9, 8], [22, 29, 36, 43, 50, 57], []],
    [[24, 32, 40, 48, 56], [25, 34, 43, 52, 61], [17, 18, 19, 20, 21, 22, 23], [9, 2], [8, 0], [], [], [], []],
    [[25, 33, 41, 49, 57], [26, 35, 44, 53, 62], [18, 19, 20, 21, 22, 23], [10, 3], [9, 1], [8], [16], [24], []],
    [[26, 34, 42, 50, 58], [27, 36, 45, 54, 63], [19, 20, 21, 22, 23], [11, 4], [10, 2], [9, 0], [17, 16], [25, 32], []],
    [[27, 35, 43, 51, 59], [28, 37, 46, 55], [20, 21, 22, 23], [12, 5], [11, 3], [10, 1], [18, 17, 16], [26, 33, 40], []],
    [[28, 36, 44, 52, 60], [29, 38, 47], [21, 22, 23], [13, 6], [12, 4], [11, 2], [19, 18, 17, 16], [27, 34, 41, 48], []],
    [[29, 37, 45, 53, 61], [30, 39], [22, 23], [14, 7], [13, 5], [12, 3], [20, 19, 18, 17, 16], [28, 35, 42, 49, 56], []],
    [[30, 38, 46, 54, 62], [31], [23], [15], [14, 6], [13, 4], [21, 20, 19, 18, 17, 16], [29, 36, 43, 50, 57], []],
    [[31, 39, 47, 55, 63], [], [], [], [15, 7], [14, 5], [22, 21, 20, 19, 18, 17, 16], [30, 37, 44, 51, 58], []],
    [[32, 40, 48, 56], [33, 42, 51, 60], [25, 26, 27, 28, 29, 30, 31], [17, 10, 3], [16, 8, 0], [], [], [], []],
    [[33, 41, 49, 57], [34, 43, 52, 61], [26, 27, 28, 29, 30, 31], [18, 11, 4], [17, 9, 1], [16], [24], [32], []],
    [[34, 42, 50, 58], [35, 44, 53, 62], [27, 28, 29, 30, 31], [19, 12, 5], [18, 10, 2], [17, 8], [25, 24], [33, 40], []],
    [[35, 43, 51, 59], [36, 45, 54, 63], [28, 29, 30, 31], [20, 13, 6], [19, 11, 3], [18, 9, 0], [26, 25, 24], [34, 41, 48], []],
    [[36, 44, 52, 60], [37, 46, 55], [29, 30, 31], [21, 14, 7], [20, 12, 4], [19, 10, 1], [27, 26, 25, 24], [35, 42, 49, 56], []],
    [[37, 45, 53, 61], [38, 47], [30, 31], [22, 15], [21, 13, 5], [20, 11, 2], [28, 27, 26, 25, 24], [36, 43, 50, 57], []],
    [[38, 46, 54, 62], [39], [31], [23], [22, 14, 6], [21, 12, 3], [29, 28, 27, 26, 25, 24], [37, 44, 51, 58], []],
    [[39, 47, 55, 63], [], [], [], [23, 15, 7], [22, 13, 4], [30, 29, 28, 27, 26, 25, 24], [38, 45, 52, 59], []],
    [[40, 48, 56], [41, 50, 59], [33, 34, 35, 36, 37, 38, 39], [25, 18, 11, 4], [24, 16, 8, 0], [], [], [], []],
    [[41, 49, 57], [42, 51, 60], [34, 35, 36, 37, 38, 39], [26, 19, 12, 5], [25, 17, 9, 1], [24], [32], [40], []],
    [[42, 50, 58], [43, 52, 61], [35, 36, 37, 38, 39], [27, 20, 13, 6], [26, 18, 10, 2], [25, 16], [33, 32], [41, 48], []],
    [[43, 51, 59], [44, 53, 62], [36, 37, 38, 39], [28, 21, 14, 7], [27, 19, 11, 3], [26, 17, 8], [34, 33, 32], [42, 49, 56], []],
    [[44, 52, 60], [45, 54, 63], [37, 38, 39], [29, 22, 15], [28, 20, 12, 4], [27, 18, 9, 0], [35, 34, 33, 32], [43, 50, 57], []],
    [[45, 53, 61], [46, 55], [38, 39], [30, 23], [29, 21, 13, 5], [28, 19, 10, 1], [36, 35, 34, 33, 32], [44, 51, 58], []],
    [[46, 54, 62], [47], [39], [31], [30, 22, 14, 6], [29, 20, 11, 2], [37, 36, 35, 34, 33, 32], [45, 52, 59], []],
    [[47, 55, 63], [], [], [], [31, 23, 15, 7], [30, 21, 12, 3], [38, 37, 36, 35, 34, 33, 32], [46, 53, 60], []],
    [[48, 56], [49, 58], [41, 42, 43, 44, 45, 46, 47], [33, 26, 19, 12, 5], [32, 24, 16, 8, 0], [], [], [], []],
    [[49, 57], [50, 59], [42, 43, 44, 45, 46, 47], [34, 27, 20, 13, 6], [33, 25, 17, 9, 1], [32], [40], [48], []],
    [[50, 58], [51, 60], [43, 44, 45, 46, 47], [35, 28, 21, 14, 7], [34, 26, 18, 10, 2], [33, 24], [41, 40], [49, 56], []],
    [[51, 59], [52, 61], [44, 45, 46, 47], [36, 29, 22, 15], [35, 27, 19, 11, 3], [34, 25, 16], [42, 41, 40], [50, 57], []],
    [[52, 60], [53, 62], [45, 46, 47], [37, 30, 23], [36, 28, 20, 12, 4], [35, 26, 17, 8], [43, 42, 41, 40], [51, 58], []],
    [[53, 61], [54, 63], [46, 47], [38, 31], [37, 29, 21, 13, 5], [36, 27, 18, 9, 0], [44, 43, 42, 41, 40], [52, 59], []],
    [[54, 62], [55], [47], [39], [38, 30, 22, 14, 6], [37, 28, 19, 10, 1], [45, 44, 43, 42, 41, 40], [53, 60], []],
    [[55, 63], [], [], [], [39, 31, 23, 15, 7], [38, 29, 20, 11, 2], [46, 45, 44, 43, 42, 41, 40], [54, 61], []],
    [[56], [57], [49, 50, 51, 52, 53, 54, 55], [41, 34, 27, 20, 13, 6], [40, 32, 24, 16, 8, 0], [], [], [], []],
    [[57], [58], [50, 51, 52, 53, 54, 55], [42, 35, 28, 21, 14, 7], [41, 33, 25, 17, 9, 1], [40], [48], [56], []],
    [[58], [59], [51, 52, 53, 54, 55], [43, 36, 29, 22, 15], [42, 34, 26, 18, 10, 2], [41, 32], [49, 48], [57], []],
    [[59], [60], [52, 53, 54, 55], [44, 37, 30, 23], [43, 35, 27, 19, 11, 3], [42, 33, 24], [50, 49, 48], [58], []],
    [[60], [61], [53, 54, 55], [45, 38, 31], [44, 36, 28, 20, 12, 4], [43, 34, 25, 16], [51, 50, 49, 48], [59], []],
    [[61], [62], [54, 55], [46, 39], [45, 37, 29, 21, 13, 5], [44, 35, 26, 17, 8], [52, 51, 50, 49, 48], [60], []],
    [[62], [63], [55], [47], [46, 38, 30, 22, 14, 6], [45, 36, 27, 18, 9, 0], [53, 52, 51, 50, 49, 48], [61], []],
    [[63], [], [], [], [47, 39, 31, 23, 15, 7], [46, 37, 28, 19, 10, 1], [54, 53, 52, 51, 50, 49, 48], [62], []],
    [[], [], [57, 58, 59, 60, 61, 62, 63], [49, 42, 35, 28, 21, 14, 7], [48, 40, 32, 24, 16, 8, 0], [], [], [], []],
    [[], [], [58, 59, 60, 61, 62, 63], [50, 43, 36, 29, 22, 15], [49, 41, 33, 25, 17, 9, 1], [48], [56], [], []],
    [[], [], [59, 60, 61, 62, 63], [51, 44, 37, 30, 23], [50, 42, 34, 26, 18, 10, 2], [49, 40], [57, 56], [], []],
    [[], [], [60, 61, 62, 63], [52, 45, 38, 31], [51, 43, 35, 27, 19, 11, 3], [50, 41, 32], [58, 57, 56], [], []],
    [[], [], [61, 62, 63], [53, 46, 39], [52, 44, 36, 28, 20, 12, 4], [51, 42, 33, 24], [59, 58, 57, 56], [], []],
    [[], [], [62, 63], [54, 47], [53, 45, 37, 29, 21, 13, 5], [52, 43, 34, 25, 16], [60, 59, 58, 57, 56], [], []],
    [[], [], [63], [55], [54, 46, 38, 30, 22, 14, 6], [53, 44, 35, 26, 17, 8], [61, 60, 59, 58, 57, 56], [], []],
    [[], [], [], [], [55, 47, 39, 31, 23, 15, 7], [54, 45, 36, 27, 18, 9, 0], [62, 61, 60, 59, 58, 57, 56], [], []]
  ]
  public static srcSquareToDstSquareToDirection: Array<Array<Direction>> = 
  [
  [Direction.INVALID, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.NORTH, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHEAST],
    [Direction.WEST, Direction.INVALID, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.NORTHWEST, Direction.NORTH, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID],
    [Direction.WEST, Direction.WEST, Direction.INVALID, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.INVALID, Direction.NORTHWEST, Direction.NORTH, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID],
    [Direction.WEST, Direction.WEST, Direction.WEST, Direction.INVALID, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.NORTH, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID],
    [Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.INVALID, Direction.EAST, Direction.EAST, Direction.EAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.NORTH, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.NORTHEAST, Direction.NORTHWEST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID],
    [Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.INVALID, Direction.EAST, Direction.EAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.NORTH, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID],
    [Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.INVALID, Direction.EAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.NORTH, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID],
    [Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.NORTHWEST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH],
    [Direction.SOUTH, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.NORTH, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID],
    [Direction.SOUTHWEST, Direction.SOUTH, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.WEST, Direction.INVALID, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.NORTHWEST, Direction.NORTH, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHEAST],
    [Direction.INVALID, Direction.SOUTHWEST, Direction.SOUTH, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.WEST, Direction.WEST, Direction.INVALID, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.INVALID, Direction.NORTHWEST, Direction.NORTH, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID],
    [Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.SOUTH, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.WEST, Direction.WEST, Direction.WEST, Direction.INVALID, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.NORTH, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID],
    [Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.SOUTH, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.INVALID, Direction.EAST, Direction.EAST, Direction.EAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.NORTH, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.NORTHEAST, Direction.NORTHWEST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID],
    [Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.SOUTH, Direction.SOUTHEAST, Direction.INVALID, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.INVALID, Direction.EAST, Direction.EAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.NORTH, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID],
    [Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.SOUTH, Direction.SOUTHEAST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.INVALID, Direction.EAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.NORTH, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID],
    [Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.SOUTH, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH],
    [Direction.SOUTH, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.NORTH, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID],
    [Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.SOUTH, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.WEST, Direction.INVALID, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.NORTHWEST, Direction.NORTH, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID],
    [Direction.SOUTHWEST, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.SOUTH, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.WEST, Direction.WEST, Direction.INVALID, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.INVALID, Direction.NORTHWEST, Direction.NORTH, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHEAST],
    [Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.SOUTH, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.WEST, Direction.WEST, Direction.WEST, Direction.INVALID, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.NORTH, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID],
    [Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.SOUTH, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.INVALID, Direction.EAST, Direction.EAST, Direction.EAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.NORTH, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.NORTHEAST, Direction.NORTHWEST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID],
    [Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.SOUTH, Direction.SOUTHEAST, Direction.INVALID, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.INVALID, Direction.EAST, Direction.EAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.NORTH, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID],
    [Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.SOUTH, Direction.SOUTHEAST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.INVALID, Direction.EAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.NORTH, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID],
    [Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.SOUTH, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH],
    [Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.NORTH, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID],
    [Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.SOUTH, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.WEST, Direction.INVALID, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.NORTHWEST, Direction.NORTH, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID],
    [Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.SOUTH, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.WEST, Direction.WEST, Direction.INVALID, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.INVALID, Direction.NORTHWEST, Direction.NORTH, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID],
    [Direction.SOUTHWEST, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.SOUTH, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.WEST, Direction.WEST, Direction.WEST, Direction.INVALID, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.NORTH, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHEAST],
    [Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.SOUTH, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.INVALID, Direction.EAST, Direction.EAST, Direction.EAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.NORTH, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.NORTHEAST, Direction.NORTHWEST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID],
    [Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.SOUTH, Direction.SOUTHEAST, Direction.INVALID, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.INVALID, Direction.EAST, Direction.EAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.NORTH, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID],
    [Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.SOUTH, Direction.SOUTHEAST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.INVALID, Direction.EAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.NORTH, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID],
    [Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.SOUTH, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH],
    [Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.NORTH, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID],
    [Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.SOUTH, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.WEST, Direction.INVALID, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.NORTHWEST, Direction.NORTH, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID],
    [Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.SOUTH, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.WEST, Direction.WEST, Direction.INVALID, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.INVALID, Direction.NORTHWEST, Direction.NORTH, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID],
    [Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHEAST, Direction.SOUTHWEST, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.SOUTH, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.WEST, Direction.WEST, Direction.WEST, Direction.INVALID, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.NORTH, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID],
    [Direction.SOUTHWEST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.SOUTH, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.INVALID, Direction.EAST, Direction.EAST, Direction.EAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.NORTH, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.NORTHEAST],
    [Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.SOUTH, Direction.SOUTHEAST, Direction.INVALID, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.INVALID, Direction.EAST, Direction.EAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.NORTH, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID],
    [Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.SOUTH, Direction.SOUTHEAST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.INVALID, Direction.EAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.NORTH, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID],
    [Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.SOUTH, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.INVALID, Direction.NORTH],
    [Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.NORTH, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID],
    [Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.SOUTH, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.WEST, Direction.INVALID, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.NORTHWEST, Direction.NORTH, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID],
    [Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.SOUTH, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.WEST, Direction.WEST, Direction.INVALID, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.INVALID, Direction.NORTHWEST, Direction.NORTH, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID],
    [Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHEAST, Direction.SOUTHWEST, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.SOUTH, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.WEST, Direction.WEST, Direction.WEST, Direction.INVALID, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.NORTH, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID],
    [Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.SOUTH, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.INVALID, Direction.EAST, Direction.EAST, Direction.EAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.NORTH, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.NORTHEAST, Direction.INVALID],
    [Direction.SOUTHWEST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.SOUTH, Direction.SOUTHEAST, Direction.INVALID, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.INVALID, Direction.EAST, Direction.EAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.NORTH, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.NORTH, Direction.INVALID, Direction.NORTHEAST],
    [Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.SOUTH, Direction.SOUTHEAST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.INVALID, Direction.EAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.NORTH, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.NORTH, Direction.INVALID],
    [Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.SOUTH, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.NORTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.INVALID, Direction.NORTH],
    [Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.NORTH, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID],
    [Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.SOUTH, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.WEST, Direction.INVALID, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.NORTHWEST, Direction.NORTH, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID],
    [Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.SOUTH, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.WEST, Direction.WEST, Direction.INVALID, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.INVALID, Direction.NORTHWEST, Direction.NORTH, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID],
    [Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHEAST, Direction.SOUTHWEST, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.SOUTH, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.WEST, Direction.WEST, Direction.WEST, Direction.INVALID, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.NORTH, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID],
    [Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.SOUTH, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.INVALID, Direction.EAST, Direction.EAST, Direction.EAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.NORTH, Direction.NORTHEAST, Direction.INVALID, Direction.INVALID],
    [Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.SOUTH, Direction.SOUTHEAST, Direction.INVALID, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.INVALID, Direction.EAST, Direction.EAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.NORTH, Direction.NORTHEAST, Direction.INVALID],
    [Direction.SOUTHWEST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.SOUTH, Direction.SOUTHEAST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.INVALID, Direction.EAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.NORTH, Direction.NORTHEAST],
    [Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.SOUTH, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.NORTHWEST, Direction.NORTH],
    [Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHEAST, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST],
    [Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.SOUTH, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.WEST, Direction.INVALID, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST],
    [Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.SOUTH, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.WEST, Direction.WEST, Direction.INVALID, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST],
    [Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHEAST, Direction.SOUTHWEST, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.SOUTH, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.WEST, Direction.WEST, Direction.WEST, Direction.INVALID, Direction.EAST, Direction.EAST, Direction.EAST, Direction.EAST],
    [Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.SOUTH, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.INVALID, Direction.EAST, Direction.EAST, Direction.EAST],
    [Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.SOUTHEAST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.SOUTH, Direction.SOUTHEAST, Direction.INVALID, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.INVALID, Direction.EAST, Direction.EAST],
    [Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.SOUTH, Direction.SOUTHEAST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.INVALID, Direction.EAST],
    [Direction.SOUTHWEST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.INVALID, Direction.SOUTH, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.INVALID, Direction.SOUTHWEST, Direction.SOUTH, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.WEST, Direction.INVALID]
  ]
  public static squareToKnightActionSquares: Array<Array<number>> =
  [
    [10, 17],
    [11, 16, 18],
    [12, 8, 17, 19],
    [13, 9, 18, 20],
    [14, 10, 19, 21],
    [15, 11, 20, 22],
    [12, 21, 23],
    [13, 22],
    [18, 2, 25],
    [19, 3, 24, 26],
    [20, 4, 0, 16, 25, 27],
    [21, 5, 1, 17, 26, 28],
    [22, 6, 2, 18, 27, 29],
    [23, 7, 3, 19, 28, 30],
    [4, 20, 29, 31],
    [5, 21, 30],
    [26, 10, 1, 33],
    [27, 11, 2, 0, 32, 34],
    [28, 12, 3, 1, 8, 24, 33, 35],
    [29, 13, 4, 2, 9, 25, 34, 36],
    [30, 14, 5, 3, 10, 26, 35, 37],
    [31, 15, 6, 4, 11, 27, 36, 38],
    [7, 5, 12, 28, 37, 39],
    [6, 13, 29, 38],
    [34, 18, 9, 41],
    [35, 19, 10, 8, 40, 42],
    [36, 20, 11, 9, 16, 32, 41, 43],
    [37, 21, 12, 10, 17, 33, 42, 44],
    [38, 22, 13, 11, 18, 34, 43, 45],
    [39, 23, 14, 12, 19, 35, 44, 46],
    [15, 13, 20, 36, 45, 47],
    [14, 21, 37, 46],
    [42, 26, 17, 49],
    [43, 27, 18, 16, 48, 50],
    [44, 28, 19, 17, 24, 40, 49, 51],
    [45, 29, 20, 18, 25, 41, 50, 52],
    [46, 30, 21, 19, 26, 42, 51, 53],
    [47, 31, 22, 20, 27, 43, 52, 54],
    [23, 21, 28, 44, 53, 55],
    [22, 29, 45, 54],
    [50, 34, 25, 57],
    [51, 35, 26, 24, 56, 58],
    [52, 36, 27, 25, 32, 48, 57, 59],
    [53, 37, 28, 26, 33, 49, 58, 60],
    [54, 38, 29, 27, 34, 50, 59, 61],
    [55, 39, 30, 28, 35, 51, 60, 62],
    [31, 29, 36, 52, 61, 63],
    [30, 37, 53, 62],
    [58, 42, 33],
    [59, 43, 34, 32],
    [60, 44, 35, 33, 40, 56],
    [61, 45, 36, 34, 41, 57],
    [62, 46, 37, 35, 42, 58],
    [63, 47, 38, 36, 43, 59],
    [39, 37, 44, 60],
    [38, 45, 61],
    [50, 41],
    [51, 42, 40],
    [52, 43, 41, 48],
    [53, 44, 42, 49],
    [54, 45, 43, 50],
    [55, 46, 44, 51],
    [47, 45, 52],
    [46, 53]
  ]
  public static squareToP1PawnMoveSquares: Array<Array<number>> =
  [
    [8],
    [9],
    [10],
    [11],
    [12],
    [13],
    [14],
    [15],
    [16, 24],
    [17, 25],
    [18, 26],
    [19, 27],
    [20, 28],
    [21, 29],
    [22, 30],
    [23, 31],
    [24],
    [25],
    [26],
    [27],
    [28],
    [29],
    [30],
    [31],
    [32],
    [33],
    [34],
    [35],
    [36],
    [37],
    [38],
    [39],
    [40],
    [41],
    [42],
    [43],
    [44],
    [45],
    [46],
    [47],
    [48],
    [49],
    [50],
    [51],
    [52],
    [53],
    [54],
    [55],
    [56],
    [57],
    [58],
    [59],
    [60],
    [61],
    [62],
    [63],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    []
  ]
  public static squareToP2PawnMoveSquares: Array<Array<number>> =
  [
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [0],
    [1],
    [2],
    [3],
    [4],
    [5],
    [6],
    [7],
    [8],
    [9],
    [10],
    [11],
    [12],
    [13],
    [14],
    [15],
    [16],
    [17],
    [18],
    [19],
    [20],
    [21],
    [22],
    [23],
    [24],
    [25],
    [26],
    [27],
    [28],
    [29],
    [30],
    [31],
    [32],
    [33],
    [34],
    [35],
    [36],
    [37],
    [38],
    [39],
    [40, 32],
    [41, 33],
    [42, 34],
    [43, 35],
    [44, 36],
    [45, 37],
    [46, 38],
    [47, 39],
    [48],
    [49],
    [50],
    [51],
    [52],
    [53],
    [54],
    [55]
  ]
  public static squareToP1PawnAbilitySquares: Array<Array<number>> =
  [
    [9],
    [8, 10],
    [9, 11],
    [10, 12],
    [11, 13],
    [12, 14],
    [13, 15],
    [14],
    [17],
    [16, 18],
    [17, 19],
    [18, 20],
    [19, 21],
    [20, 22],
    [21, 23],
    [22],
    [25],
    [24, 26],
    [25, 27],
    [26, 28],
    [27, 29],
    [28, 30],
    [29, 31],
    [30],
    [33],
    [32, 34],
    [33, 35],
    [34, 36],
    [35, 37],
    [36, 38],
    [37, 39],
    [38],
    [41],
    [40, 42],
    [41, 43],
    [42, 44],
    [43, 45],
    [44, 46],
    [45, 47],
    [46],
    [49],
    [48, 50],
    [49, 51],
    [50, 52],
    [51, 53],
    [52, 54],
    [53, 55],
    [54],
    [57],
    [56, 58],
    [57, 59],
    [58, 60],
    [59, 61],
    [60, 62],
    [61, 63],
    [62],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    []
  ]
  public static squareToP2PawnAbilitySquares: Array<Array<number>> =
  [
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [1],
    [0, 2],
    [1, 3],
    [2, 4],
    [3, 5],
    [4, 6],
    [5, 7],
    [6],
    [9],
    [8, 10],
    [9, 11],
    [10, 12],
    [11, 13],
    [12, 14],
    [13, 15],
    [14],
    [17],
    [16, 18],
    [17, 19],
    [18, 20],
    [19, 21],
    [20, 22],
    [21, 23],
    [22],
    [25],
    [24, 26],
    [25, 27],
    [26, 28],
    [27, 29],
    [28, 30],
    [29, 31],
    [30],
    [33],
    [32, 34],
    [33, 35],
    [34, 36],
    [35, 37],
    [36, 38],
    [37, 39],
    [38],
    [41],
    [40, 42],
    [41, 43],
    [42, 44],
    [43, 45],
    [44, 46],
    [45, 47],
    [46],
    [49],
    [48, 50],
    [49, 51],
    [50, 52],
    [51, 53],
    [52, 54],
    [53, 55],
    [54]
  ]
}
